### ISSUE TITLE
Launch Screen Design

### ISSUE THREAD

**Issue by pgabettie** [beaumanvienna/marley#70]
discussion of splash screen, shown on marley launch.

**Comment by pgabettie** [comment]
THESE ARE WORKING IDEAS, essentially concepts, subsequent revisions will be more refined and more visually polished.

This is the current screen.
![current](https://user-images.githubusercontent.com/1754173/106397306-b07e0000-63da-11eb-89a4-55f021e54c19.jpg)

Using this as the start point, I kept most of the elements as of this first revision.
- Marley Logo (redesign logo is tentative, I'd like to post on /r/designcritiques subreddit and get input)
- loading files
- Current Cores Logos

I've added
- background screen shot of "classic games".  This was my initial thought.  I have many working version of this idea.
- "Loading XX%" if this is possible.  This gives context the files loading, and let's user see progress of load.  If this can be done simply, it'd be a nice add.
![splash2-v1](https://user-images.githubusercontent.com/1754173/106397444-7c570f00-63db-11eb-824d-48594e0f8e9f.jpg)
![splash1-v1](https://user-images.githubusercontent.com/1754173/106397450-8aa52b00-63db-11eb-809f-c756bc83d8a3.jpg)

I have other working version with:
MONKEY ISLAND! lol
Zelda
Metroid
(I'm reference top games survey lists for games.  Finding well composed, quality resolution screen shots has been difficult.  I make need to take my own).

**Comment by beaumanvienna** [comment]
I think the screens are all leaning too much toward a specific game. Marley plays lots of games, so we need something more generic. 

Here are design elements: 

 * water/pool/ice as background. This can later be changed to a jungle or mountain scenery or beach 
 * There should be one element that is pixelized ("Hey this program is dealing with big pixels!")
 * One or more "adventure" elements (rum barrel, Indian spears, a volcano, tiki idols, treasure chest, Caribbean island/beach/palm tree/ surfer shack)
    Less is more of course. Maybe simply two pixelized, crossing spears and some native tribe feather headress?

![splash](https://user-images.githubusercontent.com/7109443/106522085-0662ae80-6494-11eb-8c0f-6dec5f4ec387.png)

**Comment by beaumanvienna** [comment]
@pgabettie The loading "Loading 99%" and "files/that/are/loading/now.cpp" is not really needed anymore. The old interface had only one line from which to start a game. Marley used to search all configured game paths for ROMs, throw them in a huge list and show them in the launch bar. Hence the file names scrolling through during the splash screen. The new interface has a file browser - no more recursive search. The only exception is for bios files. However, Marley copies bios files into its config folder, so it would only search recursively the very first time.

**Comment by pgabettie** [comment]
![marley-splash-v2](https://user-images.githubusercontent.com/1754173/110403965-03874a80-804c-11eb-9b1a-5aef4e8f96b4.png)

**Comment by pgabettie** [comment]
This is the current iteration of the splash.  I personally feel this is a better option than the current splash.  Future iterations would build on this.  Ship, final logo, character(s) of some kind along with animation.  Doing these take time, that is better spent - I feel at least for now - is better spent on the user interface.  I do want to further iterate on this and the logo.

I like this because:
- It has a colorful, but not too bright, color pallete
- has a good adventured-themed foundation to build on
- "work in progress" makes clear what it is and that it will chang.  (I think it's more human than "beta" or version)
- it's symmetrical and balanced.
- this retro style is much clearer than the current pixalted/retro styled splash.

If you'd like to continue using the current splash, I'm fine with that, but I'd like to move on to UI now for a while.

**Comment by beaumanvienna** [comment]
We can definitely go ahead with this one

**Comment by beaumanvienna** [comment]
@pgabettie Please fork Marley and replace 

`resources/splash_overlay.png` and 
`resources/splash_spritesheet.png`.

Please add a new png called
`resources/static_background.png`.

Please do this first (= in the next few days) as I don't simply want to copy your design over under my name. Your design needs to be committed by you. 

In more detail: we need to think about how to pull the animation for the background off. We do not want to save the entire pic 20 times in the sprite sheet. We can split the background into two parts: a static background and the sprite sheet. We can change the current dimensions of the sprite sheet as needed. The mountains, beach, trees, and clouds can go into the static part. This one we have only once to save disk space and loading time. The sprite sheet should only contain the areas of animation: for the sky I'd like to expand on the fireworks idea. I will change the works to multi-color to look more obvious. Then you can work on a slow movement in the water ( a change every two or three frames) including a small reflection of the light source.

I will work on the fireworks on Saturday, so that we can wrap this topic up by Sunday.

Regarding the 3D reflection of the logo, I don't think we need this anymore. The picture is consistent and the viewer can parse it: 3D background and all elements of the foreground layer have the same depth. That should work.

**Comment by beaumanvienna** [comment]
actually, put the sky also into the static part. I can create yet another overly for the fireworks
